common:
  htmlUrl: http://vott.ru
  rssUrl: http://vott.ru/rss.xml
develop:
  token: "590210984:AAEOy4fh6iCkOq6h2VZbZdezIFsIDrYHXBw"
  chatId: "@vott_dev"
  # интервал проверки новых сообщений в секундах
  checkInterval: 60
production:
  token: "510786249:AAGD4bI7lFc444W5HzX-TaGhlTm7s1BlU1E"
  chatId: "@vott_rus"
  # интервал проверки новых сообщений в секундах
  checkInterval: 300
