common:
  botErrorsForReloadProxy: 5
  fetchErrorsForReloadProxy: 3
  getProxyUrl: 'https://api.getproxylist.com/proxy?protocol=http'
  htmlUrl: 'https://vott.ru'
  rssUrl: 'https://vott.ru/rss.xml'
  chatId: $CHAT_ID
  token: $TOKEN
  proxy:
    - '85.198.142.186:8081'
    - '176.36.164.240:48039'
    - '134.249.156.3:82'
    - '92.52.186.123:32329'
    - '188.163.170.130:41209'
    - '176.104.52.46:47578'
    - '77.120.3.159:8080'
    - '176.36.118.116:32542'
develop:
  checkInterval: 90
production:
  checkInterval: 600
